### ISSUE TITLE
haos_extend.c does not build with recent versions of OpenIPMI

### ISSUE THREAD

**Issue by fabbione** [Seneca-CDOT/simengine#150]
trying to build simengine on Fedora34 (and later Centos8 / RHEL8):

OpenIPMI-devel-2.0.31

+ gcc -shared -o /home/fabbione/rpmbuild/BUILD/simengine-3.36/haos_extend.so -fPIC /home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c: In function 'bmc_set_chassis_control':
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c:118:8: error: 'CHASSIS_CONTROL_POWER' undeclared (first use in this function); did you mean 'IPMI_CONTROL_POWER'?
  118 |   case CHASSIS_CONTROL_POWER:
      |        ^~~~~~~~~~~~~~~~~~~~~
      |        IPMI_CONTROL_POWER
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c:118:8: note: each undeclared identifier is reported only once for each function it appears in
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c:119:8: error: 'CHASSIS_CONTROL_RESET' undeclared (first use in this function); did you mean 'IPMI_CONTROL_RESET'?
  119 |   case CHASSIS_CONTROL_RESET:
      |        ^~~~~~~~~~~~~~~~~~~~~
      |        IPMI_CONTROL_RESET
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c:120:8: error: 'CHASSIS_CONTROL_BOOT_INFO_ACK' undeclared (first use in this function)
  120 |   case CHASSIS_CONTROL_BOOT_INFO_ACK:
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c:121:8: error: 'CHASSIS_CONTROL_BOOT' undeclared (first use in this function)
  121 |   case CHASSIS_CONTROL_BOOT:
      |        ^~~~~~~~~~~~~~~~~~~~
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c:122:8: error: 'CHASSIS_CONTROL_GRACEFUL_SHUTDOWN' undeclared (first use in this function); did you mean 'HW_OP_CAN_GRACEFUL_SHUTDOWN'?
  122 |   case CHASSIS_CONTROL_GRACEFUL_SHUTDOWN:
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |        HW_OP_CAN_GRACEFUL_SHUTDOWN
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c: In function 'ipmi_sim_module_init':
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c:179:8: warning: implicit declaration of function 'ipmi_mc_alloc_unconfigured' [-Wimplicit-function-declaration]
  179 |   rv = ipmi_mc_alloc_unconfigured(sys, 0x20, &bmc_mc);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/fabbione/rpmbuild/BUILD/simengine-3.36/enginecore/ipmi_sim/haos_extend.c:188:3: warning: implicit declaration of function 'ipmi_mc_set_chassis_control_func'; did you mean 'bmc_set_chassis_control'? [-Wimplicit-function-declaration]
  188 |   ipmi_mc_set_chassis_control_func(bmc_mc, bmc_set_chassis_control, bmc_get_chassis_control, sys);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   bmc_set_chassis_control
error: Bad exit status from /var/tmp/rpm-tmp.opZSSk (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.opZSSk (%build)

**Comment by pynnl** [comment]
Hi @fabbione, the current plugin is compatible with OpenIPMI `2.0.28` at the latest as defined [here](https://github.com/Seneca-CDOT/simengine/blob/b81fe36d1632cfa92d373abe0c6d848f2b53e656/rpm/specfiles/simengine-core.spec#L10). Does your task require the latest version of OpenIPMI?

**Comment by fabbione** [comment]
@pynnl well, we do require simengine to build with the current version of OpenIPMI shipped with the OS. Downgrading specific packages brings other issues in the big picture.

**Comment by Tsu-ba-me** [comment]
@fabbione @pynnl @ctyler SInce I'll investigate and hopefully resolve this.

**Comment by Tsu-ba-me** [comment]
Update:

1. https://github.com/Seneca-CDOT/simengine/blob/b81fe36d1632cfa92d373abe0c6d848f2b53e656/enginecore/ipmi_sim/haos_extend.c#L26
The first problem involves missing symbols when building with `OpenIPMI > 2.0.28`. Including `serv.h` doesn't work in the later versions of OpenIPMI because it no longer includes `mcserv.h` after being migrated to `lanserv.h` (see [this OpenIPMI change](https://sourceforge.net/p/openipmi/code/ci/c7b58da82e7176e556a33dee7104109bc2045e9f/tree/lanserv/OpenIPMI/serv.h?diff=3eb2545e485d4cd680d0ef18dc4c3728b59f2dd0)). To resolve this problem, we can include `mcserv.h` when using newer versions; note that `mcserv.h` also includes the new `lanserv.h` (originally `serv.h` in the older version).
2. The second problem involves the renaming and relocation of a function (`'ipmi_mc_alloc_unconfigured' -> 'is_mc_alloc_unconfigured'`). This function was originally declared in `mcserv.h` and defined in `bmc.c`, but the declaration was moved to `ipmi_sim.h` in the same commit where the function rename happened (see [this OpenIPMI change](https://sourceforge.net/p/openipmi/code/ci/26e0921e77b6db359e7b018e8d439fcd1222d891/tree/lanserv/OpenIPMI/mcserv.h?diff=7421f86fb03827dfdd84b69c4c1663ec5757e19f)); however, `ipmi_sim.h` is not included in the OpenIPMI-devel package.

**Comment by fabbione** [comment]
Just attempted to build on Centos8:
+ gcc -shared -o /root/rpmbuild/BUILD/simengine-3.37/haos_extend.so -fPIC -D OPENIPMI_POST_2_0_30 /root/rpmbuild/BUILD/simengine-3.37/enginecore/ipmi_sim/haos_extend.c
/root/rpmbuild/BUILD/simengine-3.37/enginecore/ipmi_sim/haos_extend.c: In function 'ipmi_sim_module_init':
/root/rpmbuild/BUILD/simengine-3.37/enginecore/ipmi_sim/haos_extend.c:185:8: warning: implicit declaration of function 'is_mc_alloc_unconfigured' [-Wimplicit-function-declaration]
   rv = is_mc_alloc_unconfigured(sys, 0x20, &bmc_mc);
        ^~~~~~~~~~~~~~~~~~~~~~~~
+ exit 0

The code builds, but this error means that there will likely be a runtime issue for unresolved symbols.

**Comment by Tsu-ba-me** [comment]
This issue has been mentioned in the second problem of [the comment above](https://github.com/Seneca-CDOT/simengine/issues/150#issuecomment-889545294) and in [the related PR](https://github.com/Seneca-CDOT/simengine/pull/152).

The function was originally available in a header until version 2.0.30. Since 2.0.31, the function declaration was moved to a header that is not included in the OpenIPMI-devel RPM package. However, I've confirmed that the IPMI simulation can run with this extension (more specifically, the function in question has executed).

I currently don't see a "proper" patch to this issue.
